name: Release to Modrinth

on:
    workflow_dispatch:
        inputs:
            target:
                description: "Publish Targets"
                type: choice
                options:
                    - both
                    - modrinth
                    - curseforge
                default: both
                required: true
            version:
                description: "Version tag (e.g. v1.2.0)"
                required: true
            min_version:
                description: "Min Minecraft Version (inclusive)"
                required: true
                default: "1.21.1"
            max_version:
                description: "Max Minecraft Version (not inclusive)"
                required: true
                default: "1.22.0"
            release_type:
                description: "release | beta | alpha"
                required: true
                default: "release"

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - name: Build datapack zip
              run: |
                  set -euo pipefail
                  rm -f disable-biome-spawns-*.zip
                  cd pack
                  zip -r "../disable-biome-spawns-${{ inputs.version }}+mc${{ inputs.min_version }}.zip" .

            # -------- BOTH --------
            - name: Publish to Modrinth & CurseForge
              if: ${{ inputs.target == 'both' }}
              uses: Kir-Antipov/mc-publish@v3.3
              with:
                  modrinth-id: ${{ secrets.MODRINTH_PROJECT_ID }}
                  modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
                  curseforge-id: ${{ secrets.CURSEFORGE_PROJECT_ID }}
                  curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

                  files: |
                      disable-biome-spawns-${{ inputs.version }}+mc${{ inputs.min_version }}.zip
                  name: disable-biome-spawns-${{ inputs.version }}+mc${{ inputs.min_version }}
                  version: ${{ inputs.version }}
                  version-type: ${{ inputs.release_type }}
                  changelog-file: CHANGELOG.md

                  loaders: |
                      datapack
                  game-versions: |
                      >=${{ inputs.min_version }}
                      <${{ inputs.max_version }}
                  game-version-filter: releases

            # -------- MODRINTH ONLY --------
            - name: Publish to Modrinth
              if: ${{ inputs.target == 'modrinth' }}
              uses: Kir-Antipov/mc-publish@v3.3
              with:
                  modrinth-id: ${{ secrets.MODRINTH_PROJECT_ID }}
                  modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

                  files: |
                      disable-biome-spawns-${{ inputs.version }}+mc${{ inputs.min_version }}.zip
                  name: disable-biome-spawns-${{ inputs.version }}+mc${{ inputs.min_version }}
                  version: ${{ inputs.version }}
                  version-type: ${{ inputs.release_type }}
                  changelog-file: CHANGELOG.md

                  loaders: |
                      datapack
                  game-versions: |
                      >=${{ inputs.min_version }}
                      <${{ inputs.max_version }}
                  game-version-filter: releases

            # -------- CURSEFORGE ONLY --------
            - name: Publish to CurseForge
              if: ${{ inputs.target == 'curseforge' }}
              uses: Kir-Antipov/mc-publish@v3.3
              with:
                  curseforge-id: ${{ secrets.CURSEFORGE_PROJECT_ID }}
                  curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

                  files: |
                      disable-biome-spawns-${{ inputs.version }}+mc${{ inputs.min_version }}.zip
                  name: disable-biome-spawns-${{ inputs.version }}+mc${{ inputs.min_version }}
                  version: ${{ inputs.version }}
                  version-type: ${{ inputs.release_type }}
                  changelog-file: CHANGELOG.md

                  loaders: |
                      datapack
                  game-versions: |
                      >=${{ inputs.min_version }}
                      <${{ inputs.max_version }}
                  game-version-filter: releases
