name: Release to CurseForge

on:
    workflow_dispatch:
        inputs:
            version:
                description: "Version tag"
                required: true
            game_versions:
                description: "Minecraft Versions, One per line (e.g. 1.21.1)"
                required: true
                default: |-
                    1.21.1
            release_type:
                description: "release | beta | alpha"
                required: true
                default: "release"

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - name: Build datapack zip
              run: |
                  set -euo pipefail
                  rm -f disable-biome-spawns-*.zip
                  cd pack
                  zip -r ../disable-biome-spawns-${{ inputs.version }}+mc${{ inputs.game_versions }}.zip .

            - name: Publish to CurseForge
              uses: Kir-Antipov/mc-publish@v3.3
              with:
                  curseforge-id: ${{ secrets.CURSEFORGE_PROJECT_ID }}
                  curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

                  files: |
                      disable-biome-spawns-${{ inputs.version }}+mc${{ inputs.game_versions }}.zip
                  name: ${{ inputs.version }}
                  version: ${{ inputs.version }}
                  version-type: ${{ inputs.release_type }}
                  changelog-file: CHANGELOG.md
                  game-versions: ${{ inputs.game_versions }}
                  loaders: |
                      datapack
